### ISSUE TITLE
build issues cygwin64/win7

### ISSUE THREAD

**Issue by devel-chm** [Corion/app-shadertoy#1]
I was able to build the current git of shadertoy (as of commit 11960520f009073a885bdc4d841815ba2365833c) on my cygwin64 system with the following issues:

- a bunch of pointer-int conversion errors (see attached log)
- link failed due to missing -lX11 argument (added by hand and it finished)
- tests seem to work partially (some bad exit conditions may be problems)
- couldn't run shadertoy seascape because it require OpenGL 4 :-(
- it would be nice to have test/demo/example that doesn't require the bleeding edge OpenGL

I hope this is useful.  Much improved from the first build where it failed out of the box.

[app-shadertoy-log.txt](https://github.com/Corion/app-shadertoy/files/573223/app-shadertoy-log.txt)

**Comment by devel-chm** [comment]
As we fold the GLEW bindings into the mainstream OpenGL, we'll definitely need to support the various levels of the OpenGL API---at least the modern OpenGL 2.x and up.

**Comment by Corion** [comment]
Thanks for testing things!

The missing X11 headers should be no problem as I'm already using Devel::CheckOS, and adding them as a Cygwin (or, more likely, non-Windows, non-Mac) link option should remedy that.

Yes, I haven't looked or checked at the pointer conversion things yet. I'm currently working on adding some basic sanity checks.

Shadertoy itself will require OpenGL 3.x features, but I'm also looking at finding some interesting things to do with lower OpenGL versions. OpenGL::Glew itself should work on any OpenGL version, but no test program is there to display fancy things with it...

**Comment by Corion** [comment]
The build should be fixed in ed05622

**Comment by devel-chm** [comment]
There are some nuances with unix versus windows versus macos versus... linking.
I should have included my fix originally---since I knew what it was.  I've attached a git format-patch.

Some things to note:
1. The link libraries need to be in proper order to satisfy dependencies, -lGL needs stuff from X11 so the -lX11 must follow.  I would recommend the same order for your default case.
2. The cygwin X11 server now uses the native windows OpenGL driver under the hood so you don't need the windows libraries.  However, it is possible to build MinGW binaries but I would suggest that be a MinGW option.
3. Since const-c.inc and const-xs.inc are generated files, you don't want them in the git repo and should add them to the .gitignore file.
4. A lot of the shader work is available since OpenGL 2.x and 3.x.  I don't know enough about the changes to know which features require which API.  Is the limit on OpenGL 4 being detected by a feature request or is it being set "by hand"?

This is exciting stuff.  I'm working out some needed steps to complete the merge and OpenGL development.  Do you have an account on sf.net?  I would like to add you as a developer to our git there.  Still TBD what makes the most sense for overall repo management for POGL (Perl OpenGL) going forwards.

--Chris

[0001-Fix-cygwin64-link-problem-with-missing-lX11.txt](https://github.com/Corion/app-shadertoy/files/573340/0001-Fix-cygwin64-link-problem-with-missing-lX11.txt)

**Comment by wchristian** [comment]
@chm how did you determine that it wants  opengl 4? From what i can see on the code it mainly wants opengl 3.3.

I may also be able to provide less exciting shaders that run on older hardware.

**Comment by devel-chm** [comment]
I found a typo in the code.  Also, I have a commit which takes the generated files out of git.  Not sure what you want to do here but it is annoying to have differences shown for files that are from the repo as compared to the correct ones generated on one's own platform.

[0001-Fix-typo-for-glGetShaderInfoLog.txt](https://github.com/Corion/app-shadertoy/files/573402/0001-Fix-typo-for-glGetShaderInfoLog.txt)
[0002-Don-t-put-generated-files-under-git.txt](https://github.com/Corion/app-shadertoy/files/573401/0002-Don-t-put-generated-files-under-git.txt)

@wchristian: I got this output trying to run the seascape and saw the OpenGL4.pm:

>  perl -Mblib scripts/shadertoy.pl shaders/seascape.fragment 
> Initialized using GLEW 2.0.0
> 3.0 Mesa 11.0.4
> You have an old version of OpenGL loaded (3.0), you won't have much fun. at /cygdrive/e/chm/pogl/app-shadertoy/blib/lib/OpenGL/Shader/OpenGL4.pm line 51, <> line 1.
> Created VAO: 0 at scripts/shadertoy.pl line 134, <> line 1.
> 00000000 at scripts/shadertoy.pl line 141, <> line 1.
> Use of uninitialized value in subroutine entry at scripts/shadertoy.pl line 146, <> line 1.
> Couldn't get shader attribute 'pos', compilation error? at scripts/shadertoy.pl line 148, <> line 1.
> Segmentation fault (core dumped)

I get the same failure for all the other shaders under shaders/.  I hope that there is something interesting that can be done with 3.0.  Maybe I can try using the windows GL instead to get the full version this PC is capable.  I'll check if the new cygwin X11 version should be at a higher version or what...

**Comment by Corion** [comment]
It is my strong intention to put the generated files unter version control as I intend to generate them before distribution and I want their history in source control as well. This makes it especially easy to find when the autogeneration changes its results.

For the shader failure, you only have OpenGL 3.0, but the shaders (resp. the standard wrapper around the fragment shader) requires OpenGL 3.3 minimum:

  #version 330 core
I haven't investigated how to lower this requirement. As Shadertoy.com is able to run with less, there should be a way to get at least some of the stuff to run on lower OpenGL versions. This is more a problem of App::ShaderToy than of the OpenGL(::Glew) bindings IMO :-)

**Comment by devel-chm** [comment]
Apparently the native WGL windows support needs to be explicitly enabled via

> export LIBGL_USE_WGL=1

After that I see OpenGL version 4.5 from Nvidia and have much shader joy!
![cygwin_seascape_joy](https://cloud.githubusercontent.com/assets/789881/20033629/7755c624-a37b-11e6-816e-2f908f6489ab.png)

**Comment by devel-chm** [comment]
I get the following failures to run:

>  perl -Mblib scripts/shadertoy.pl shaders/foggy-mountain.fragment 
> Initialized using GLEW 2.0.0
> 4.5.0 NVIDIA 347.52
> Created VAO: 0 at scripts/shadertoy.pl line 134, <> line 1.
> 00000000 at scripts/shadertoy.pl line 141, <> line 1.
> Use of uninitialized value in subroutine entry at scripts/shadertoy.pl line 146, <> line 1.
> Couldn't get shader attribute 'pos', compilation error? at scripts/shadertoy.pl line 148, <> line 1.
> Segmentation fault (core dumped)

and

>  perl -Mblib scripts/shadertoy.pl shaders/realistic-eye.fragment 
> Initialized using GLEW 2.0.0
> 4.5.0 NVIDIA 347.52
> Created VAO: 0 at scripts/shadertoy.pl line 134, <> line 1.
> 00000000 at scripts/shadertoy.pl line 141, <> line 1.
> Use of uninitialized value in subroutine entry at scripts/shadertoy.pl line 146, <> line 1.
> Couldn't get shader attribute 'pos', compilation error? at scripts/shadertoy.pl line 148, <> line 1.
> Segmentation fault (core dumped)

Note also the Segmentation fault on exit.  Otherwise looks good so far.

**Comment by Corion** [comment]
Woo hoo! Let me note that somewhere in the documentation of OpenGL::Glew just that we find it again somewhere. I would assume that having this in a BEGIN block somewhere should enable the lastest and greatest on Cygwin:

BEGIN {
    export LIBGL_USE_WGL=1
}

**Comment by Corion** [comment]
I think these two shaders require features that I haven't implemented yet, namely textures or buffers...

**Comment by devel-chm** [comment]
except that LIBGL_USE_WGL is an environment variable.  Maybe $ENV{LIBGL_USE_WGL} = ... would work.

I had a problem with a Prima segfault on exit that I reported to Dmitry.  He says it is a bug.  Maybe it is the same as here---you are using Prima, correct?

**Comment by Corion** [comment]
Am 05.11.2016 um 22:26 schrieb devel-chm:

> except that LIBGL_USE_WGL is an environment variable. Maybe
> $ENV{LIBGL_USE_WGL} = ... would work.
> D'oh, yes ;)
> 
> I had a problem with a Prima segfault on exit that I reported to Dmitry.
> He says it is a bug. Maybe it is the same as here---you are using Prima,
> correct?
> Yes, I am using Prima - so far, it seems quite portable and suitable for 
> a live-editor; suitable for Shadertoy, not for OpenGL(::Glew) overall

-max

**Comment by devel-chm** [comment]
Prima is very nice as a portable GUI and with respect to OpenGL(::Glew) it provides a context and infrastructure to use OpenGL.  There are many different ways to get an OpenGL context to render in: GLUT/FreeGLUT, GLFW, Qt, wxWidgets, GLX,...  As i mentioned previously, OpenGL includes FreeGLUT/GLUT bindings.  I now believe that to be inappropriate as the source of the OpenGL context is independent of the OpenGL and should be factored out.

**Comment by dk** [comment]
The segfault was in indeed, but in code applied after 1.49 . If you're using the snapshot from CPAN, it must be something else. If not, the fix was already pushed to github

**Comment by devel-chm** [comment]
I'll re-sync with github and report back.  Thanks.

**Comment by devel-chm** [comment]
That was it.  Apologies for any confusion.

**Comment by devel-chm** [comment]
I verified that setting $ENV{LIBGL_USE_WGL}=1 in a BEGIN block at the top of shadertoy,pl does enable full WGL OpenGL features.  Patch attached.

[0001-Set-ENV-LIBGL_USE_WGL-1-for-cygwin-to-use-WGL-OpenGL.txt](https://github.com/Corion/app-shadertoy/files/573861/0001-Set-ENV-LIBGL_USE_WGL-1-for-cygwin-to-use-WGL-OpenGL.txt)

**Comment by devel-chm** [comment]
I just tried the latest Prima, Prima-OpenGL, and app-shadertoy from git on another cygwin64/win7 system.  Things work but I when I resize the window, the region displayed stays the same rather than filling the new window size.  I'll test on the original system and let you know if I see the same behavior there.

![bad-resize-seascape](https://cloud.githubusercontent.com/assets/789881/20039528/84adafa6-a413-11e6-952e-6fb1a43c2a26.png)

**Comment by dk** [comment]
I think that this can be an issue that cygwin build links against win32 native libs, while (the default) cygwin Prima build doesn't use them, but uses X server instead. I couldn't build the default build for cygwin, but I could when I replaced the libs to '-lX11 -lGL' in Makefile.PL; but again, having built it that way, I couldn't reproduce the issue with the resizeable window, all works just fine on my setup.

**Comment by devel-chm** [comment]
The resize problem may be machine specific (drivers, antivirus,...) which is why I plan to test on the original system.  In addition, the X11 support for native WGL OpenGL is new so it could also be related to the version of the XWin.exe server on the system.

**Comment by devel-chm** [comment]
The windows resize and display just fine on the other cygwin64/win7 system which has completely different versions of the cygwin dll and the XWin server.  I'm going to put this on the back burner until I can find a limited example that can generate this specific issue.

**Comment by devel-chm** [comment]
I just upgraded the problem cygwin install to the latest X11 and cygwin versions and now the shadertoy window resizes correctly.
