### ISSUE TITLE
OpenGL::Glew to POGL2 update

### ISSUE THREAD

**Issue by devel-chm** [Corion/app-shadertoy#13]
This is an informational issue only.  I'm planning to set up the initial start at POGL2 using your OpenGL::Glew from app-shadertoy.  Some thoughts on development are on the [POGL2 site](https://sourceforge.net/p/pogl/wiki/POGL2%20Development%20Plans/) on sourceforge.

I also plan on starting an irc for Perl OpenGL development to go with the initial start at a github repository.  My plan is that development will take place on github but that the reference/release repository will be the mirror at sf.net.

I'm planning for an initial OpenGL developers release based on the new GLEW generated bindings by the end of the weekend.  There are a number of issues needed to be sorted out with the API and all before an official release.  This is to avoid breaking the Perl OpenGL APIs unnecessarily.

Max, please let me know your sf.net user id and I can add you as a developer on that end as well.

**Comment by Corion** [comment]
I don't have an sf.net user.

I have prototypically attempted to integrate OpenGL::Glew into the current OpenGL source, but I will have to learn more about which files depend on what and have to think about the build order etc., so you trying to integrate this into OpenGL is most welcome!

**Comment by devel-chm** [comment]
We now have a #pogl IRC chat on irc.perl.org so l(oo|ur)k there for conversation...

I've started putting the pieces together.  I think maybe the module should be OpenGL::Modern which can be merged into the OpenGL distribution at some point when it makes sense.  That will avoid problems with backwards support as the final API settles down.

**Comment by devel-chm** [comment]
I've added Corion and wchristian as collaborators to my opengl-modern repository.  This is the OpenGL::Glew from your app-shadertoy extracted and converted to OpenGL::Modern which is the module name that seems to make the most sense.

Max, please verify that OpenGL::Modern can replace your OpenGL::Glew internal code.  That will simplify the modern perl OpenGL bindings by keeping all of our development in a single place.

I'm regretting naming the repo opengl-modern instead of OpenGL-Modern and unless I hear horrible things, I will probably change the capitalization to match the perl distribution name for OpenGL::Modern.

**Comment by devel-chm** [comment]
OpenGL::Modern repo is at [https://github.com/devel-chm/opengl-modern](https://github.com/devel-chm/opengl-modern)

It should be able to replace the current OpenGL::Glew in app-shadertoy.  Please verify.  If there are any problems, open an issue on that repo.  Note you have been added as a contributor.

**Comment by devel-chm** [comment]
Max has verified that the OpenGL::Modern module which was derived from his implementation of OpenGL::Glew works in place of his use of OpenGL::Glew.  At this point further OpenGL::Modern development is taking place at the [github repository OpenGL-Modern](https://github.com/devel-chm/OpenGL-Modern).

I am closing this ticket.  To participate further in OpenGL::Modern development, please go to the OpenGL-Modern repository.  You can participate in discusion, dialog related to Perl OpenGL bindings at the \#pogl channel at irc.perl.org.  The Perl OpenGL mailing lists are by subscription only and hosted at sf.net.  Go to the [Perl OpenGL mailing lists](https://sourceforge.net/p/pogl/mailman/?source=navbar) to subscribe, view or search archived messages.
