### ISSUE TITLE
change shader file extensions so github recognizes them

### ISSUE THREAD

**Issue by wchristian** [Corion/app-shadertoy#15]
Right now it doesn't grok .fragment or .geometry, but it handles .frag and .geom fine:

https://github.com/wchristian/Microidium/blob/master/share/post_process.frag
https://github.com/wchristian/Microidium/blob/master/share/screen_target.geom
https://github.com/wchristian/Microidium/blob/master/share/timings.vert

**Comment by Corion** [comment]
Yep - even though I'm not convinced this "standard" is so great, it adds source highlighting and likely will push the statistics more in the correct direction, so I'm renaming the shaders ;)
