### ISSUE TITLE
bindings not generated for glMapBuffer/glMapBufferARG

### ISSUE THREAD

**Issue by devel-chm** [Corion/app-shadertoy#18]
I noticed that only these two functions were missing from the OpenGL::Modern as compared with OpenGL.  The good news is we found a bug and that Modern::OpenGL is a complete superset of the routines from OpenGL (modulo the differences in API/naming as "\_[cps]"

I'm going to look at the code generation but it doesn't have a lot of comments so may take a while to figure it out...

**Comment by Corion** [comment]
If I remember right, you can pass the function name on the command line to restrict the generation to that name. Most likely one of the parser regexes is too specific ...

Looking at include/GL/glee.h, the thing is that glMapBuffer is a #define not a typedef. That's the likely problem and applies to glUnmapBuffer as well.Likely adding the #define to the RE fixes everything

-max

Am 14. Dezember 2016 16:14:11 MEZ, schrieb devel-chm <notifications@github.com>:
>I noticed that only these two functions were missing from the
>OpenGL::Modern as compared with OpenGL.  The good news is we found a
>bug and that Modern::OpenGL is a complete superset of the routines from
>OpenGL (modulo the differences in API/naming as "\_[cps]"
>
>I'm going to look at the code generation but it doesn't have a lot of
>comments so may take a while to figure it out...
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Corion/app-shadertoy/issues/18

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Corion** [comment]
This should be fixed in OpenGL::Modern via  0a29733
