### ISSUE TITLE
fails on perl5-18 (probably)

### ISSUE THREAD

**Issue by dk** [Corion/app-shadertoy#2]
y> perl -Mblib scripts/shadertoy.pl shaders/seascape.fragment
Prototype after '%' for OpenGL::ScreenCapture::capture : %options at /nfs/home/dmka/src/app-shadertoy/blib/lib/OpenGL/ScreenCapture.pm line 33.
Illegal character in prototype for OpenGL::ScreenCapture::capture : %options at /nfs/home/dmka/src/app-shadertoy/blib/lib/OpenGL/ScreenCapture.pm line 33.
No quotelike operator found after prefix at ";

=head1 FUNCTION...", detected at offset 92Global symbol "%options" requires explicit package name at /nfs/home/dmka/src/app-shadertoy/blib/lib/OpenGL/ScreenCapture.pm line 34.
Global symbol "%options" requires explicit package name at /nfs/home/dmka/src/app-shadertoy/blib/lib/OpenGL/ScreenCapture.pm line 35.
Global symbol "%options" requires explicit package name at /nfs/home/dmka/src/app-shadertoy/blib/lib/OpenGL/ScreenCapture.pm line 36.
Global symbol "%options" requires explicit package name at /nfs/home/dmka/src/app-shadertoy/blib/lib/OpenGL/ScreenCapture.pm line 38.
Global symbol "%options" requires explicit package name at /nfs/home/dmka/src/app-shadertoy/blib/lib/OpenGL/ScreenCapture.pm line 38.
Global symbol "%options" requires explicit package name at /nfs/home/dmka/src/app-shadertoy/blib/lib/OpenGL/ScreenCapture.pm line 41.
Global symbol "%options" requires explicit package name at /nfs/home/dmka/src/app-shadertoy/blib/lib/OpenGL/ScreenCapture.pm line 42.
Global symbol "%options" requires explicit package name at /nfs/home/dmka/src/app-shadertoy/blib/lib/OpenGL/ScreenCapture.pm line 44.
Global symbol "%options" requires explicit package name at /nfs/home/dmka/src/app-shadertoy/blib/lib/OpenGL/ScreenCapture.pm line 44.
Global symbol "%options" requires explicit package name at /nfs/home/dmka/src/app-shadertoy/blib/lib/OpenGL/ScreenCapture.pm line 45.
Global symbol "%options" requires explicit package name at /nfs/home/dmka/src/app-shadertoy/blib/lib/OpenGL/ScreenCapture.pm line 50.
Global symbol "%options" requires explicit package name at /nfs/home/dmka/src/app-shadertoy/blib/lib/OpenGL/ScreenCapture.pm line 51.
Global symbol "%options" requires explicit package name at /nfs/home/dmka/src/app-shadertoy/blib/lib/OpenGL/ScreenCapture.pm line 52.
Global symbol "%options" requires explicit package name at /nfs/home/dmka/src/app-shadertoy/blib/lib/OpenGL/ScreenCapture.pm line 53.
Global symbol "%options" requires explicit package name at /nfs/home/dmka/src/app-shadertoy/blib/lib/OpenGL/ScreenCapture.pm line 55.
Global symbol "%options" requires explicit package name at /nfs/home/dmka/src/app-shadertoy/blib/lib/OpenGL/ScreenCapture.pm line 56.
Global symbol "%options" requires explicit package name at /nfs/home/dmka/src/app-shadertoy/blib/lib/OpenGL/ScreenCapture.pm line 56.
Global symbol "%options" requires explicit package name at /nfs/home/dmka/src/app-shadertoy/blib/lib/OpenGL/ScreenCapture.pm line 61.
Global symbol "%options" requires explicit package name at /nfs/home/dmka/src/app-shadertoy/blib/lib/OpenGL/ScreenCapture.pm line 62.
Global symbol "%options" requires explicit package name at /nfs/home/dmka/src/app-shadertoy/blib/lib/OpenGL/ScreenCapture.pm line 70.
Global symbol "%options" requires explicit package name at /nfs/home/dmka/src/app-shadertoy/blib/lib/OpenGL/ScreenCapture.pm line 71.
Compilation failed in require at scripts/shadertoy.pl line 7.
BEGIN failed--compilation aborted at scripts/shadertoy.pl line 7.
[1]    15023 exit 255   perl -Mblib scripts/shadertoy.pl shaders/seascape.fragment

**Comment by dk** [comment]
(also, Filter::signatures was not in Makefile.PL's prerequisites)

**Comment by Corion** [comment]
Whoops - I've added Filter::signatures in e444179, this should fix the problem

**Comment by Corion** [comment]
Dmitry, did the last version resp. the fix (by adding Filter::signatures) work for you? Filter::signatures is a hack to make signatures work (in a limited way) on older Perl versions as well, and if it still doesn't work that would mean there is a problem with Filter::signatures (or Filter::Simple)...

If everything works for you without needing to fix my code, I'll close the issue ;)

**Comment by dk** [comment]
No it still has same problem. I'd guess the problem indeed is with Filter::signatures

**Comment by Corion** [comment]
Tracked it down - it was an error because Filter::signatures could not parse empty signatures like

```
sub Load() {
```

This is fixed with Filter::signatures 0.6 and should now also work for you.

**Comment by dk** [comment]
It works now! But has other issues - I'll open another ticket. Thank you!
