### ISSUE TITLE
shaders/geometry-test.geometry crashes cygwin64/win7

### ISSUE THREAD

**Issue by devel-chm** [Corion/app-shadertoy#9]
I don't know if this was working when I last tried all the shaders.  Things are much better now.  All the shaders now work on my cygwin64/win7 system except for geometry-test which crashes with the following error.  I took a quick look but am not knowledgeable enough re shaders to figure out what might be the problem....

> Application built with libpng-1.6.20 but running with 1.6.24
Initialized using GLEW 2.0.0
4.5.0 NVIDIA 353.82
Odd number of elements in hash assignment at scripts/shadertoy.pl line 116.
Segmentation fault (core dumped)

This is with this version from git: commit 09cc12123c9f4dbff2383f5c3ac9856ef0a8d9b2

**Comment by Corion** [comment]
No, this must always have been broken. The geometry shader file is empty, leading to the odd-sized hash, leading to a coredump on program exit. There is far too much fancy idiomatic Perl code in the shader initialization, which I will have to redo.

**Comment by devel-chm** [comment]
The latest git dde443 no longer crashes.  It gives some error messages and loads the default shader:

>  perl -Mblib scripts/shadertoy.pl shaders/geometry-test.geometry 
Initialized using GLEW 2.0.0
4.5.0 NVIDIA 347.52
<<shaders/geometry-test.geometry>> at scripts/shadertoy.pl line 136.
Something went wrong, looking at log at /cygdrive/e/chm/pogl/app-shadertoy/blib/lib/OpenGL/Shader/OpenGL4.pm line 148.
Error in Shader: Link shader to program: Geometry info
\-------------
(0) : error C6022: No input primitive type
(0) : error C6029: No output primitive type
\
The shader 'shaders/geometry-test.geometry' did not load, using default shader at scripts/shadertoy.pl line 411.

Much improved!

**Comment by Corion** [comment]
Thanks for the feedback, closing!
